### ISSUE TITLE
🐛  باگ: مشکل کالبک تبلیغ جایزه‌ای

### ISSUE THREAD

**Issue by mahdi-malv** [tapsellorg/TapsellPlusSDK-B4APlugin#3]
<div dir='rtl'>

**شرح باگ در پلاگین**:
پس از پایان نمایش تبلیغ جایزه‌ای sub مورد نظر فراخوانی نمیشود

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
-

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:
- نمایش یک تبلیغ جایزه‌ای
- تاخیر چند ثانیه‌ای بعد از اتمام و نبستن
- بستن

**پکیج نیم برنامه‌**: ``
-

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  
-

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

دلیل اینکه این مشکل پیش میاد اینه که Subهای تعریف شده توسط دولپر وابسته به اکتیویتی اپ هست و در صورتی که reward نمایش داده بشه اکتیویتی کاربر تو state=paused هست و subها فراخوانی نمیشن

در حال حاضر با یه delay این کارو انجام میده که همه‌ی کیس‌ها رو پوشش نمیده

</div>

**Comment by bijan64** [comment]
بنظر مشکل کتابخونه ست
در نسخه قدیمی تپسل این مشکل وجود نداشت
کال بک خروج از تبلیغ هم عمل نمیکنه که بشه کارو پیش برد
سایر سیستم های تبلیغاتی با همین نسخه نرم افزار مشکلی ندارن و کال بکشون مشکلی نداره

**Comment by mahdi-malv** [comment]
2.1.4 has a fix for this. Re-open if you still face this.
