### ISSUE TITLE
مشکل فراخوانی در کال بک

### ISSUE THREAD

**Issue by arplayer** [tapsellorg/TapsellPlusSDK-B4APlugin#4]
سلام
لطفا مشکل فراخوانی در کال بک بعد از نمایش کامل تبلیغ و یا خروج از تبلیغ را زودتر حل نمایید
کال بک ها در نسخه قدیمی تپسل مشکلی نداشت
ممنون

**Comment by mahdi-malv** [comment]
سلام. نسخه‌ی ۲.۱.۴ باید این مورد رو مرتفع کنه
لطفا تست کنید
