### ISSUE TITLE
🐛  باگ: خطا در تارگت 30 به بالا

### ISSUE THREAD

**Issue by mzelecom** [tapsellorg/TapsellPlusSDK-B4APlugin#5]
<div dir='rtl'>

**شرح باگ در پلاگین**:
در صورتی که دسترسی AddPermission(android.permission.READ_PHONE_STATE) داده نشه خطا میده .
این دسترسی نباید اجباری باشه .لطفا رفع کنید.
تشکر

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
(SecurityException) java.lang.SecurityException: getDataNetworkTypeForSubscriber

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

</div>

**Comment by MortezaNedaei** [comment]
سلام وقت بخیر
پلاگین تپسل از این دسترسی استفاده نمی کند.
لطفا پلاگین های دیگه رو بررسی بفرمایید.
